# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: LGPL-3.0-or-later
version = 1
SPDX-PackageName = "nextcloud/kitinerary-bin"
SPDX-PackageSupplier = "Nextcloud GmbH <https://nextcloud.com/impressum/>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud-libraries/kitinerary-bin"

[[annotations]]
path = ["composer.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = ["bin/kitinerary-extractor"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Volker Krause <vkrause@kde.org>"
SPDX-License-Identifier = "LGPL-2.0-or-later"
