name: Commit checks
on: pull_request

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.2.0
  fixup-squash-commits:
    name: Fixup and squash commits
    runs-on: ubuntu-latest
    steps:
      - name: Run check
        uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs:
      - conventional-commits
      - fixup-squash-commits
    if: always()
    name: commit-summary
    steps:
      - name: Conventional commit summary
        run: if ${{ needs.conventional-commits.result != 'success' && needs.conventional-commits.result != 'skipped' }}; then exit 1; fi
      - name: Fixup summary
        run: if ${{ needs.fixup-squash-commits.result != 'success' && needs.fixup-squash-commits.result != 'skipped' }}; then exit 1; fi
